permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Jasmine Graphic Designer"
  discription: |
A graphic Designer

font_url: "https://use.typekit.net/pbl6vxx.css"
font_url: "https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i&display=swap"

  rationales:
    typefaces.primary: |
      AdornS Pomander
    typefaces.secondary: |
      Avenir Next
    typefaces.tertiary: |
      PT Serif was selected beacause it is a simple and easily readable text for body copy. This will help the user read when the font size is smaller then 14pt.
    colors.primary: |

    colors.secondary: |

collections:
  products:
    output: true
defaults:
- scope:
    path: _products
  values:
    layout: product
