permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Jasmine Graphic Designer"
  discription: |
font_url: "https://use.typekit.net/pbl6vxx.css"
font_url: "https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i&display=swap"
