title: "Buttons"
description: |
  Lots of different buttons for that can be used through the webiste, to view more in detail, to add to the cart and many more.

patterns:
  basic:
    title: "Basic"
    description: Should be used in almost all situations
    fields:
      - name: text
        type: string
        example: "Add to Cart"
      - name: btn-text
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Add this item to your cart"
  ghost:
    title: "Ghost"
    description: The ghost button should only be used on banners and in situations where the background is a photo
    width: 320
    fields:
      - name: text
        type: string
        example: "Add to Cart"
  wide:
    title: "Wide Button"
    description: The wide button should only be used on cards and in situations where the text withing the button is longer and needs ectra room to fit the surrounding information
    fields:
      - name: text
        type: string
        example: "Add to Cart"
      - name: aria
        type: string
        example: "Add this item to your cart"
  white-ghost:
    title: "White"
    description: This button should be used on the darker backgrounds so it can be read and stand out
    fields:
      - name: text
        type: string
        example: "See collection"
      - name: url
        type: url
        example: "/products/"
      - name: aria
        type: string
        example: "Add this item to your cart"
