title: "Buttons"
description: |
  Lots of different buttons for that can be used through the webiste, to view more in detail, to add to the cart and many more.

patterns:
  basic:
    title: "Basic"
    description: Should be used in almost all situations, when used on white or purple background the button should be blue, and of the button is placed on blue background the button should be pruple.
    width: 200
    fields:
      - name: text
        type: string
        example: "Learn More"
      - name: btn-text
        type: string
        example: "#"
      - name: aria
        type: string
        example: "Add this item to your cart"
      - name: url
        type: url
        example: "#"

  ghost:
    title: "Ghost"
    description: The ghost button should only be used on banners and in situations where the background is a photo or a pruple background colour
    width: 200
    fields:
      - name: text
        type: string
        example: "Learn More"
      - name: url
        type: url
        example: "#"
  ghost-purple:
    title: "Ghost Purple"
    description: The purple ghost button should only be used on banners and in situations where the background is a photo or blue background colour
    width: 200
    fields:
      - name: text
        type: string
        example: "Learn More"
      - name: url
        type: url
        example: "#"
  wide:
    title: "Wide Button"
    description: The wide button should only be used when the text that needs to go inside is more then 2 wordds.
    width: 320
    fields:
      - name: text
        type: string
        example: "Get in Touch"
      - name: aria
        type: string
        example: "Get in Touch with Jasmine"
      - name: url
        type: url
        example: "#"
  basic-purple:
    title: "Basic Purple Button"
    description: Should be used in other situations opposite to blue button, when used on blue background the button should be purple.
    width: 320
    fields:
      - name: text
        type: string
        example: "Get in Touch"
      - name: aria
        type: string
        example: "Get in Touch with Jasmine"
      - name: url
        type: url
        example: "#"
