title: "colors"
description:
    This section will be for my case study for branding to showcase the colours.

patterns:
  colors:
    fields:
      - name: text
        type: string
        example: "FFF"
